import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedcteagorizationlistwidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcteagorizationlistwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcteagorizationlistwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcteagorizationlistwidget/generated/GeneratedGroup12Widget.dart';

/* Component Cteagorization list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCteagorizationlistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 52.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 78.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 24.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 220.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 24.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 24.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 24.0,
                child: GeneratedGroup11Widget(),
              )
            ]),
      ),
    ));
  }
}
