import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedGroup35633Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedProfileWidget35.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedSurveyWidget7.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedProfileWidget32.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdreviewWidget8.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdcreationWidget8.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedLivestreamWidget7.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedGroup35634Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedHomepageWidget3.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedHomepageWidget2.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedSurveyWidget4.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedFulllistWidget2.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedSurveyWidget5.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedLivestreamWidget6.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedProfileWidget25.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdreviewWidget6.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedSIGNINWidget1.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedFulllistWidget1.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdcreationWidget7.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedGroup35633Widget1.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdreviewWidget9.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedOnboarding3Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdreviewWidget7.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedLivestreamWidget9.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdcreationWidget9.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdcreationWidget10.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedProfileWidget29.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedOwnadWidget.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedLivestreamWidget8.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedAdreviewWidget5.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedSurveyWidget6.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedExploreWidget30.dart';
import 'package:flutterapp/ad_20appapp/generatedarabicwidget/generated/GeneratedREGISTERWidget1.dart';

/* Frame ARABIC
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedARABICWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 7200.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 9472.0,
                      height: 7200.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 232, 232, 232),
                              ),
                            ),
                            Positioned(
                              left: 4655.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedSurveyWidget4(),
                            ),
                            Positioned(
                              left: 5123.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedSurveyWidget5(),
                            ),
                            Positioned(
                              left: 5591.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedSurveyWidget6(),
                            ),
                            Positioned(
                              left: 6059.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedSurveyWidget7(),
                            ),
                            Positioned(
                              left: 7929.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedLivestreamWidget6(),
                            ),
                            Positioned(
                              left: 8451.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedLivestreamWidget7(),
                            ),
                            Positioned(
                              left: 3458.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedProfileWidget25(),
                            ),
                            Positioned(
                              left: 3204.0,
                              top: 6376.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 609.0,
                              child: GeneratedGroup35633Widget(),
                            ),
                            Positioned(
                              left: 3579.0,
                              top: 6376.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 609.0,
                              child: GeneratedGroup35634Widget(),
                            ),
                            Positioned(
                              left: 3954.0,
                              top: 6375.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 609.0,
                              child: GeneratedGroup35633Widget1(),
                            ),
                            Positioned(
                              left: 2054.0,
                              top: 3837.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedExploreWidget30(),
                            ),
                            Positioned(
                              left: 2054.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedHomepageWidget2(),
                            ),
                            Positioned(
                              left: 2028.0,
                              top: 574.0,
                              right: null,
                              bottom: null,
                              width: 613.0,
                              height: 40.0,
                              child: GeneratedComponent4Widget(),
                            ),
                            Positioned(
                              left: 2562.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedHomepageWidget3(),
                            ),
                            Positioned(
                              left: 3070.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedFulllistWidget1(),
                            ),
                            Positioned(
                              left: 2054.0,
                              top: 2305.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedFulllistWidget2(),
                            ),
                            Positioned(
                              left: 4187.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1560.0,
                              child: GeneratedAdreviewWidget5(),
                            ),
                            Positioned(
                              left: 4655.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1232.0,
                              child: GeneratedAdreviewWidget6(),
                            ),
                            Positioned(
                              left: 2544.0,
                              top: 2305.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1077.0,
                              child: GeneratedOwnadWidget(),
                            ),
                            Positioned(
                              left: 5591.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1234.0,
                              child: GeneratedAdreviewWidget7(),
                            ),
                            Positioned(
                              left: 5123.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1232.0,
                              child: GeneratedAdreviewWidget8(),
                            ),
                            Positioned(
                              left: 6059.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedAdreviewWidget9(),
                            ),
                            Positioned(
                              left: 6777.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedLivestreamWidget8(),
                            ),
                            Positioned(
                              left: 7245.0,
                              top: 670.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedLivestreamWidget9(),
                            ),
                            Positioned(
                              left: 2054.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedProfileWidget29(),
                            ),
                            Positioned(
                              left: 2522.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedProfileWidget32(),
                            ),
                            Positioned(
                              left: 2990.0,
                              top: 5063.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedProfileWidget35(),
                            ),
                            Positioned(
                              left: 4187.0,
                              top: 2545.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedAdcreationWidget7(),
                            ),
                            Positioned(
                              left: 4655.0,
                              top: 2545.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedAdcreationWidget8(),
                            ),
                            Positioned(
                              left: 5123.0,
                              top: 2545.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedAdcreationWidget9(),
                            ),
                            Positioned(
                              left: 5591.0,
                              top: 2545.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedAdcreationWidget10(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedSIGNINWidget1(),
                            ),
                            Positioned(
                              left: 831.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedREGISTERWidget1(),
                            ),
                            Positioned(
                              left: 1336.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 926.0,
                              child: GeneratedOnboarding3Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
