import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedalarmbuttonwidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedalarmbuttonwidget/generated/GeneratedReportWidget.dart';

/* Component Alarm button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlarmbuttonWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 94.0,
      height: 48.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(48.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 94.0,
              height: 48.0,
              child: GeneratedRectangle17Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 99.0,
              height: 29.0,
              child: GeneratedReportWidget(),
            )
          ]),
    ));
  }
}
