import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedbuttonwidget/generated/GeneratedSigninWidget.dart';
import 'package:flutterapp/ad_20appapp/generatedbuttonwidget/generated/GeneratedRectangle4Widget.dart';

/* Component Button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 48.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 48.0,
              child: GeneratedRectangle4Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 342.0,
              height: 18.0,
              child: GeneratedSigninWidget(),
            )
          ]),
    ));
  }
}
