import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedmypostswidget2/generated/GeneratedFrame380Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedmypostswidget2/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedmypostswidget2/generated/GeneratedFrame378Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedmypostswidget2/generated/GeneratedFrame377Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedmypostswidget2/generated/GeneratedFrame379Widget.dart';

/* Component My posts
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMypostsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 74.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 74.0,
              child: GeneratedRectangle49Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame377Widget(),
            ),
            Positioned(
              left: 107.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame378Widget(),
            ),
            Positioned(
              left: 321.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame379Widget(),
            ),
            Positioned(
              left: 214.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame380Widget(),
            )
          ]),
    ));
  }
}
