import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedhomewidget1/generated/GeneratedFrame370Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedhomewidget1/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedhomewidget1/generated/GeneratedFrame372Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedhomewidget1/generated/GeneratedFrame371Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedhomewidget1/generated/GeneratedFrame369Widget.dart';

/* Component Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 74.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 74.0,
              child: GeneratedRectangle47Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame369Widget(),
            ),
            Positioned(
              left: 107.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame370Widget(),
            ),
            Positioned(
              left: 321.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame372Widget(),
            ),
            Positioned(
              left: 214.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame371Widget(),
            )
          ]),
    ));
  }
}
