import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generateddirectmessagingwidget3/generated/GeneratedDirectmessagingWidget4.dart';
import 'package:flutterapp/ad_20appapp/generateddirectmessagingwidget3/generated/GeneratedDescriptionWidget5.dart';
import 'package:flutterapp/ad_20appapp/generateddirectmessagingwidget3/generated/GeneratedCommentsWidget4.dart';
import 'package:flutterapp/ad_20appapp/generateddirectmessagingwidget3/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/ad_20appapp/generateddirectmessagingwidget3/generated/GeneratedRectangle28Widget.dart';

/* Component Direct messaging
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDirectmessagingWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 48.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 261.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 20.0,
                child: GeneratedDirectmessagingWidget4(),
              ),
              Positioned(
                left: 142.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 21.0,
                child: GeneratedCommentsWidget4(),
              ),
              Positioned(
                left: 13.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 21.0,
                child: GeneratedDescriptionWidget5(),
              ),
              Positioned(
                left: 261.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 4.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 261.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 4.0,
                child: GeneratedRectangle28Widget(),
              )
            ]),
      ),
    ));
  }
}
