import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generateduserprofilewidget/generated/GeneratedUserimageWidget.dart';
import 'package:flutterapp/ad_20appapp/generateduserprofilewidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/ad_20appapp/generateduserprofilewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/ad_20appapp/generateduserprofilewidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/ad_20appapp/generateduserprofilewidget/generated/GeneratedNameSurnameWidget.dart';

/* Component User profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserprofileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 52.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 75.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 46.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedUserimageWidget(),
              ),
              Positioned(
                left: 92.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 16.0,
                child: GeneratedNameSurnameWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 18.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 8.0,
                height: 8.0,
                child: GeneratedRectangle24Widget(),
              )
            ]),
      ),
    ));
  }
}
