import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedmainbuttontypewidget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/ad_20appapp/generatedmainbuttontypewidget/generated/GeneratedInterestedWidget.dart';
import 'package:flutterapp/ad_20appapp/generatedmainbuttontypewidget/generated/GeneratedNotifications_noneWidget.dart';

/* Component Main button type
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainbuttontypeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 158.0,
      height: 48.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 158.0,
              height: 48.0,
              child: GeneratedRectangle18Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 122.0,
              height: 29.0,
              child: GeneratedInterestedWidget(),
            ),
            Positioned(
              left: 117.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedNotifications_noneWidget(),
            )
          ]),
    ));
  }
}
