import 'package:flutter/material.dart';

/* Rectangle Rectangle 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 129.0,
      height: 61.0,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment(-1.0, -1.0),
          end: Alignment(0.9999999457504616, 0.99999994575046),
          stops: [0.0, 1.0],
          colors: [
            Color.fromARGB(255, 28, 65, 129),
            Color.fromARGB(255, 20, 48, 131)
          ],
        ),
      ),
    ));
  }
}
