import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generateddescriptionwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/ad_20appapp/generateddescriptionwidget/generated/GeneratedDirectmessagingWidget.dart';
import 'package:flutterapp/ad_20appapp/generateddescriptionwidget/generated/GeneratedCommentsWidget.dart';

/* Component Description
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDescriptionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 48.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 262.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 18.0,
                child: GeneratedDirectmessagingWidget(),
              ),
              Positioned(
                left: 143.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 21.0,
                child: GeneratedCommentsWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 35.0,
                child: GeneratedGroup7Widget(),
              )
            ]),
      ),
    ));
  }
}
