import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedexplorewidget2/generated/GeneratedFrame375Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedexplorewidget2/generated/GeneratedFrame373Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedexplorewidget2/generated/GeneratedFrame374Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedexplorewidget2/generated/GeneratedFrame376Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedexplorewidget2/generated/GeneratedRectangle48Widget.dart';

/* Component Explore
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploreWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 74.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 74.0,
              child: GeneratedRectangle48Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame373Widget(),
            ),
            Positioned(
              left: 107.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame374Widget(),
            ),
            Positioned(
              left: 321.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame375Widget(),
            ),
            Positioned(
              left: 214.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame376Widget(),
            )
          ]),
    ));
  }
}
