import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedgroup35488widget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedgroup35488widget/generated/GeneratedSkipWidget.dart';

/* Group Group 35488
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup35488Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 287.0,
      height: 48.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 287.0,
              height: 48.0,
              child: GeneratedRectangle35Widget(),
            ),
            Positioned(
              left: 27.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 238.0,
              height: 41.0,
              child: GeneratedSkipWidget(),
            )
          ]),
    ));
  }
}
