import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedcommentswidget2/generated/GeneratedCommentsWidget3.dart';
import 'package:flutterapp/ad_20appapp/generatedcommentswidget2/generated/GeneratedRectangle26Widget2.dart';
import 'package:flutterapp/ad_20appapp/generatedcommentswidget2/generated/GeneratedDirectmessagingWidget2.dart';
import 'package:flutterapp/ad_20appapp/generatedcommentswidget2/generated/GeneratedDescriptionWidget4.dart';
import 'package:flutterapp/ad_20appapp/generatedcommentswidget2/generated/GeneratedRectangle25Widget2.dart';

/* Component Comments
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCommentsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 428.0,
        height: 48.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 262.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 18.0,
                child: GeneratedDirectmessagingWidget2(),
              ),
              Positioned(
                left: 143.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 23.0,
                child: GeneratedCommentsWidget3(),
              ),
              Positioned(
                left: 14.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 21.0,
                child: GeneratedDescriptionWidget4(),
              ),
              Positioned(
                left: 143.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 4.0,
                child: GeneratedRectangle25Widget2(),
              ),
              Positioned(
                left: 143.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 4.0,
                child: GeneratedRectangle26Widget2(),
              )
            ]),
      ),
    ));
  }
}
