import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedstandartinputwithiconwidget/generated/GeneratedTypetextWidget.dart';
import 'package:flutterapp/ad_20appapp/generatedstandartinputwithiconwidget/generated/GeneratedTexthereWidget.dart';
import 'package:flutterapp/ad_20appapp/generatedstandartinputwithiconwidget/generated/GeneratedRemove_red_eyeWidget.dart';
import 'package:flutterapp/ad_20appapp/generatedstandartinputwithiconwidget/generated/GeneratedRectangle6Widget.dart';

/* Component Standart input with icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStandartinputwithiconWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 75.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 3.0,
              right: null,
              bottom: null,
              width: 342.0,
              height: 20.0,
              child: GeneratedTexthereWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 27.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 48.0,
              child: GeneratedRectangle6Widget(),
            ),
            Positioned(
              left: 302.0,
              top: 39.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedRemove_red_eyeWidget(),
            ),
            Positioned(
              left: 19.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 69.0,
              height: 20.0,
              child: GeneratedTypetextWidget(),
            )
          ]),
    ));
  }
}
