import 'package:flutter/material.dart';

/* Rectangle Rectangle 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 129.0,
      height: 63.0,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment(-0.999999987892826, 1.0000018823020866),
          end: Alignment(1.000000005587883, -0.9999949052552495),
          stops: [0.0, 1.0],
          colors: [
            Color.fromARGB(255, 247, 195, 34),
            Color.fromARGB(255, 255, 220, 105)
          ],
        ),
      ),
    ));
  }
}
