import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedcategorylistwidget/generated/GeneratedGroup19Widget1.dart';
import 'package:flutterapp/ad_20appapp/generatedcategorylistwidget/generated/GeneratedGroup16Widget1.dart';
import 'package:flutterapp/ad_20appapp/generatedcategorylistwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcategorylistwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcategorylistwidget/generated/GeneratedGroup17Widget1.dart';
import 'package:flutterapp/ad_20appapp/generatedcategorylistwidget/generated/GeneratedGroup18Widget1.dart';

/* Component Category list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCategorylistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1004.0,
        height: 52.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 134.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 40.0,
                child: GeneratedGroup16Widget1(),
              ),
              Positioned(
                left: 250.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 40.0,
                child: GeneratedGroup18Widget1(),
              ),
              Positioned(
                left: 405.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 40.0,
                child: GeneratedGroup19Widget1(),
              ),
              Positioned(
                left: 710.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 40.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 867.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 40.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 40.0,
                child: GeneratedGroup17Widget1(),
              )
            ]),
      ),
    ));
  }
}
