import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedcomponent2widget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcomponent2widget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcomponent2widget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedcomponent2widget/generated/GeneratedGroup17Widget.dart';

/* Component Component 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponent2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 613.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 121.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 110.0,
              height: 40.0,
              child: GeneratedGroup16Widget(),
            ),
            Positioned(
              left: 244.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 94.0,
              height: 40.0,
              child: GeneratedGroup18Widget(),
            ),
            Positioned(
              left: 351.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 214.0,
              height: 40.0,
              child: GeneratedGroup19Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 40.0,
              child: GeneratedGroup17Widget(),
            )
          ]),
    ));
  }
}
