import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedstandartinputwidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/ad_20appapp/generatedstandartinputwidget/generated/GeneratedTexthereWidget1.dart';
import 'package:flutterapp/ad_20appapp/generatedstandartinputwidget/generated/GeneratedTypetextWidget1.dart';

/* Component Standart input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStandartinputWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 75.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 4.0,
              right: null,
              bottom: null,
              width: 342.0,
              height: 20.0,
              child: GeneratedTexthereWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 27.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 48.0,
              child: GeneratedRectangle6Widget1(),
            ),
            Positioned(
              left: 17.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 69.0,
              height: 20.0,
              child: GeneratedTypetextWidget1(),
            )
          ]),
    ));
  }
}
