import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedprofilewidget3/generated/GeneratedFrame383Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedprofilewidget3/generated/GeneratedFrame382Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedprofilewidget3/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedprofilewidget3/generated/GeneratedFrame384Widget.dart';
import 'package:flutterapp/ad_20appapp/generatedprofilewidget3/generated/GeneratedFrame381Widget.dart';

/* Component Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 428.0,
      height: 74.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 428.0,
              height: 74.0,
              child: GeneratedRectangle50Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame381Widget(),
            ),
            Positioned(
              left: 107.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame382Widget(),
            ),
            Positioned(
              left: 321.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame383Widget(),
            ),
            Positioned(
              left: 214.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 74.0,
              child: GeneratedFrame384Widget(),
            )
          ]),
    ));
  }
}
