import 'package:flutter/material.dart';
import 'package:flutterapp/ad_20appapp/generatedcomponent1widget/generated/GeneratedInterestedWidget1.dart';
import 'package:flutterapp/ad_20appapp/generatedcomponent1widget/generated/GeneratedNotifications_activeWidget.dart';
import 'package:flutterapp/ad_20appapp/generatedcomponent1widget/generated/GeneratedRectangle61Widget.dart';

/* Component Component 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponent1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 158.0,
      height: 48.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 158.0,
              height: 48.0,
              child: GeneratedRectangle61Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 122.0,
              height: 23.0,
              child: GeneratedInterestedWidget1(),
            ),
            Positioned(
              left: 117.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedNotifications_activeWidget(),
            )
          ]),
    ));
  }
}
